set( CPP
	main.cpp
	src/Color.cpp
	src/Text.cpp
	src/GameRenderer.cpp
	src/Input.cpp
	src/Rectangle.cpp
	src/Food.cpp
	src/Snake/Snake.cpp
	src/Snake/BodyRight.cpp
	src/Snake/BodyLeft.cpp
	src/Snake/BodyUp.cpp
	src/Snake/BodyDown.cpp
	src/Snake/BodyFactory.cpp
	src/Snake/DirectionEnum.cpp
	src/States/StateManager.cpp
	src/States/Menu.cpp
	src/States/Game.cpp
)
